[project]
name = "admin-boundaries"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["duckdb", "httpx[http2]", "psutil"]

[dependency-groups]
dev = ["obstore", "python-dotenv", "ruff"]

[tool.ruff]
fix = true

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM812", "D203", "D213", "S608"]
